image:
  file: .gitpod.prebuilt.Dockerfile
workspaceLocation: './'
tasks:
  - name: package
    before: printf '[workspace]\n\nmembers = ["package/*"]' > /workspace/Cargo.toml
    init: mkdir -p /workspace/package

vscode:
  extensions:
    - matklad.rust-analyzer
    - oraichain.cosmwasm-ide
